# Generated by Django 2.2.7 on 2019-11-26 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category of a Blog', max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Blog category',
                'verbose_name_plural': 'Blog categories',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Blog Post Header', max_length=200)),
                ('body', models.TextField(help_text='Blog Post Body')),
                ('pub_date', models.DateField(default=datetime.date.today, help_text='Date When Post Was Created')),
            ],
            options={
                'ordering': ['-pub_date', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Comment Body')),
                ('pub_date', models.DateField(default=datetime.date.today, help_text='Date When Comment Was Added')),
            ],
        ),
    ]
