# Generated by Django 2.2.7 on 2019-11-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
